COLLECTIONS-604
apache/commons-collections pull request #279
Opened 2022-02-14 07:37 UTC by Kaammill

Hi, 
I was thinking about the more uniform safe-null methods in CollectionUtils from jira task: COLLECTIONS-604. In my opinion it would be nice to have one way of treating null-safe methods.  I decided to try wit the approach that the methods that already return Boolean values could be null-save.  I would appreciate all kind of feedback on this task :)

2022-02-19 20:09 UTC, Simulant87 commented on src/main/java/org/apache/commons/collections4/CollectionUtils.java
> +
The code below will still throw a now no longer documented and expected NullPointerException if coll1 if not null but coll2 is null.
It's the same thing for the change in the method below, and possible more, I haven't read through the whole PR.

2023-03-22 17:59 UTC, Claudenw requested changes
I think you need to think about set operations.

what does `containsAny(x,y)` mean if 

- y is null?  If this is a set operation then all X contain the null set.
- x is null? If this is a set operation then the null set does not contain any other set, except perhaps the null set.

I think the same questions need to be answered for all the collections questions.

I would recommend updating the javadoc for each method so that it is clear what the various null values return.

2023-07-22 07:36 UTC, Claudenw commented
@Kaammill The more I think about this change the more I think that there is a significant issue.
Changing the code to not throw an NPE when the NPE was documented in the earlier release is (I think) a breaking change and would require a new major version.

Alternatively, a new set of classes that handle Null pointer arguments differently might be valuable.  However, this is a discussion to have on the dev mailing list.

Are you still interested in making these changes?

2024-09-03 18:36 UTC, garydgregory commented
Closing: No reply from OP in over a year.

2024-09-03 18:36 UTC, closed without merging