Reworked calculations and updated javadoc.
apache/commons-collections pull request #358
Opened 2022-11-06 16:24 UTC by Claudenw

Fix for COLLECTIONS-817

Added documentation concerning n(), intersection, and union calculations in Shape class.

Modified BloomFilter.estimatedIntersection() to account for infinite values in calculations.

2022-11-07 09:08 UTC, Claudenw commented
@aherbert I can not figure out why the checks are failing.  It looks like the code the checks are using is out of sync with the actual code base.  Do you have any suggestions for how to fix this?

2022-11-07 09:20 UTC, aherbert commented
The git diff line for AbstractBloomFilterTest:291 does not match the compile error on the CI build. So I cannot see what is wrong. Since there are new changes in master if you rebase and force push then it may fix the issue using a new base for the diff.

2022-11-07 18:57 UTC, aherbert commented on src/main/java/org/apache/commons/collections4/bloomfilter/BloomFilter.java
> +        if (Double.isNaN(d)) {
Can this happen without an error in the cardinality computation?

2022-11-07 19:21 UTC, aherbert requested changes
The feedback is mainly a bunch of whitespace issues.

However I cannot verify the code paths are tested as the coverage report is not working for this PR. It requires that the PR is based on a commit that has a coverage report. Did you branch this from master or from another PR you are simultaneously working on?

See [CodeCov missing base report](https://docs.codecov.com/docs/error-reference#section-missing-head-commit)

If you cannot get it to work then I'll check coverage locally. However the coverage report at CodeCov does specifically show if the new code lines are covered so it is nice if it works.

2022-11-07 19:21 UTC, aherbert commented on src/main/java/org/apache/commons/collections4/bloomfilter/BloomFilter.java
> +            estimate = Math.round( eOther );
Remove surrounding whitespace `(eOther)`

2022-11-07 19:21 UTC, aherbert commented on src/main/java/org/apache/commons/collections4/bloomfilter/BloomFilter.java
> +            estimate = Math.round( eThis );
Remove surrounding whitespace

2022-11-07 19:21 UTC, aherbert commented on src/main/java/org/apache/commons/collections4/bloomfilter/BloomFilter.java
> +            estimate = Math.round( eThis + eOther - eUnion );
Surrounding whitespace

2022-11-07 19:21 UTC, aherbert commented on src/main/java/org/apache/commons/collections4/bloomfilter/BloomFilter.java
> +                throw new IllegalArgumentException( "The estimated N for the union of the filters is infinite");
Remove whitespace after `(`

2022-11-07 19:21 UTC, aherbert commented on src/test/java/org/apache/commons/collections4/bloomfilter/AbstractBloomFilterTest.java
> +        BloomFilter bf5 = createFilter( getTestShape(), firstHalf);
Whitespace after `(` (and also the same issue on the next line)

2022-11-07 19:21 UTC, aherbert commented on src/main/java/org/apache/commons/collections4/bloomfilter/Shape.java
> + * <p>The calculation for the estimate of N is: {@code -(m/k) * ln( 1 - (c/m))}.  This is the calculation
Remove whitespace: `ln( 1 -` to `ln(1 -`

2022-11-07 19:21 UTC, aherbert commented on src/main/java/org/apache/commons/collections4/bloomfilter/Shape.java
> + * performed by the {@code Shape.estimateN(cardinality)} method below.  This estimates is roughly equivalent to the
`This estimate` (no estimates)

2022-11-07 19:21 UTC, aherbert commented on src/main/java/org/apache/commons/collections4/bloomfilter/Shape.java
> + * <li> if cardinality == numberOfBits, then result is infinity.</li>
`<li>if` on this line and the next

2022-11-07 19:21 UTC, aherbert commented on src/main/java/org/apache/commons/collections4/bloomfilter/Shape.java
> + * n(A) + n(b) - n( A &cup; B )
`n(A &cup; B)`

2022-11-07 19:21 UTC, aherbert commented on src/test/java/org/apache/commons/collections4/bloomfilter/AbstractBloomFilterTest.java
> +                // test split to union
Indentation of this comment is wrong

2022-11-07 19:21 UTC, aherbert commented on src/main/java/org/apache/commons/collections4/bloomfilter/BloomFilter.java
> +     * <li> if cardinality == numberOfBits, then result is Integer.MAX_VALUE.</li>
`<li>if` on this line and the next

2022-11-07 19:21 UTC, aherbert commented on src/main/java/org/apache/commons/collections4/bloomfilter/BloomFilter.java
> +            throw new IllegalArgumentException("Cardinality too large: "+cardinality());
Add whitespace around the `+` char

2022-11-07 19:21 UTC, aherbert commented on src/main/java/org/apache/commons/collections4/bloomfilter/BloomFilter.java
> +        return l>Integer.MAX_VALUE?Integer.MAX_VALUE:(int) l;
Add whitespace: `l > Integer.MAX_VALUE ? Integer.MAX_VALUE : (int) l;`

2022-11-07 19:21 UTC, aherbert commented on src/main/java/org/apache/commons/collections4/bloomfilter/BloomFilter.java
> +     * of the filters by rounding the value from the calculation described in the {@code Shape} class javadoc.</p>
`{@link Shape`

2022-11-07 19:21 UTC, aherbert commented on src/main/java/org/apache/commons/collections4/bloomfilter/BloomFilter.java
> +     * by rounding the value from the calculation described in the {@code Shape} class javadoc.</p>
`{@link Shape`

2022-11-07 19:21 UTC, aherbert commented on src/main/java/org/apache/commons/collections4/bloomfilter/BloomFilter.java
> +     * of the filters by rounding the value from the calculation described in the {@code Shape} class javadoc.</p>
`{@link Shape`

2022-11-08 19:49 UTC, aherbert requested changes
Since CodeCov is not working at the moment I ran this locally and there is no coverage of some of the new branches:
```
mvn clean test jacoco:report
open target/site/jacoco/index.html 
```
Can you have a look at those please?

2022-11-08 19:49 UTC, aherbert commented on src/main/java/org/apache/commons/collections4/bloomfilter/BloomFilter.java
> +        return estimate>Integer.MAX_VALUE?Integer.MAX_VALUE:(int) estimate;
Formatting: `estimate > Integer.MAX_VALUE ? Integer.MAX_VALUE : (int) estimate;`

Could be changed to:
```Java
return (int) Math.min(Integer.MAX_VALUE, estimate);
```
However that does obfuscate the fact there is no coverage of this edge case.

2022-11-08 19:49 UTC, aherbert commented on src/main/java/org/apache/commons/collections4/bloomfilter/BloomFilter.java
> +            // all estimated values are small values greater than 0 but less that number of bits
`less than`

2022-11-08 19:49 UTC, aherbert commented on src/main/java/org/apache/commons/collections4/bloomfilter/BloomFilter.java
> +        return l > Integer.MAX_VALUE ? Integer.MAX_VALUE : (int) l;
Could be changed to:
```Java
return (int) Math.min(Integer.MAX_VALUE, l);
```
However that does obfuscate the fact there is no coverage of this edge case.

2022-11-08 19:49 UTC, aherbert commented on src/main/java/org/apache/commons/collections4/bloomfilter/BloomFilter.java
> +        if (Double.isNaN(d)) {
Is this possible without a broken filter `cardinality` or `Shape.estimateN`?

2022-11-12 14:07 UTC, Claudenw commented on src/main/java/org/apache/commons/collections4/bloomfilter/BloomFilter.java
> +        return estimate>Integer.MAX_VALUE?Integer.MAX_VALUE:(int) estimate;
Leaving as is to verify test coverage

2022-11-12 14:07 UTC, Claudenw commented on src/main/java/org/apache/commons/collections4/bloomfilter/BloomFilter.java
> +        return l > Integer.MAX_VALUE ? Integer.MAX_VALUE : (int) l;
leaving as is to verify test coverage

2022-11-12 14:11 UTC, Claudenw commented on src/main/java/org/apache/commons/collections4/bloomfilter/BloomFilter.java
> +            // all estimated values are small values greater than 0 but less that number of bits
Modified to specify exact upper limit

2022-11-12 14:13 UTC, Claudenw commented
The only way to generate a NaN ins the BloomFilter.estimateIntersection() is with a broken cardinality.  Test case was added.

2022-11-15 19:28 UTC, aherbert requested changes
I verified that coverage is now 100%, thanks.

There are some whitespace issues to fix. I think the limit for the fully saturated BloomFilter should use `Integer.MAX_VALUE` and not `Integer.MAX_VALUE - 1`.

2022-11-15 19:28 UTC, aherbert commented on src/test/java/org/apache/commons/collections4/bloomfilter/DefaultBloomFilterTest.java
> +        for (int i=0; i<lastBits; i++) {
`for (int i = 0; i < lastBits; i++) {`

2022-11-15 19:28 UTC, aherbert commented on src/test/java/org/apache/commons/collections4/bloomfilter/DefaultBloomFilterTest.java
> +        assertEquals(last, ary[ary.length-1]);
`ary[ary.length - 1]`

2022-11-15 19:28 UTC, aherbert commented on src/test/java/org/apache/commons/collections4/bloomfilter/DefaultBloomFilterTest.java
> +    public void testLargeBitmapAsArray() {
I do not know why we need this test. It is just checking that the `asArray` function works for a maximum length filter? If this is the purpose then can we just use a filter with `bitIndex = Integer.MAX_VALUE` set to 1, e.g. by using a hasher with 1 index to populate the filter.

Is this code simply to test a fully populated max length filter, e.g. it was debugging code?

2022-11-15 19:28 UTC, aherbert commented on src/test/java/org/apache/commons/collections4/bloomfilter/DefaultBloomFilterTest.java
> +                int limit = Integer.MAX_VALUE-1;
`limit` should be Integer.MAX_VALUE. There are a lot of whitespace issues here. See the comments for the method `testLargeBitmapAsArray`.

2022-11-15 19:28 UTC, aherbert commented on src/test/java/org/apache/commons/collections4/bloomfilter/DefaultBloomFilterTest.java
> +        // the actual result of the calculation is: 46144189292
The actual result is not relevant. It could be obtained from `Shape.estimateN` to verify the result is actually above Integer.MAX_VALUE.

2022-11-15 19:28 UTC, aherbert commented on src/test/java/org/apache/commons/collections4/bloomfilter/DefaultBloomFilterTest.java
> +                int limit = Integer.MAX_VALUE-1;
`limit` should be Integer.MAX_VALUE. There are a lot of whitespace issues here. See the comments for the method `testLargeBitmapAsArray`.

2022-11-15 19:28 UTC, aherbert commented on src/test/java/org/apache/commons/collections4/bloomfilter/SimpleBloomFilterTest.java
> +        BitMapProducer producer = (p) -> {
No parentheses around `p`

2022-11-15 19:28 UTC, aherbert commented on src/test/java/org/apache/commons/collections4/bloomfilter/SimpleBloomFilterTest.java
> +        // create a producer that returns too few values
// create a producer that returns no values

2022-11-26 14:52 UTC, Claudenw commented on src/test/java/org/apache/commons/collections4/bloomfilter/SimpleBloomFilterTest.java
> +        // create a producer that returns too few values
Updated.  we are actually sending 1 long when 2 are expected.  Changed to be a  non-zero argument and test.

2022-11-26 14:53 UTC, Claudenw commented on src/test/java/org/apache/commons/collections4/bloomfilter/SimpleBloomFilterTest.java
> +        BitMapProducer producer = (p) -> {
fixed

2022-11-26 15:06 UTC, Claudenw commented on src/main/java/org/apache/commons/collections4/bloomfilter/BloomFilter.java
> +            // maximum estimate value using integer valuess is: 46144189292
The note here is that an overflow of the addition is not possible.  I updated the comment. again.

2022-11-26 15:08 UTC, Claudenw commented on src/main/java/org/apache/commons/collections4/bloomfilter/SimpleBloomFilter.java
> -            if (idxLimit < idx[0]) {
exactly

2022-11-26 15:18 UTC, Claudenw commented on src/test/java/org/apache/commons/collections4/bloomfilter/AbstractBitMapProducerTest.java
> +        // test where both producer does not process all records and function
exactly.  Updated documentation

2022-11-26 15:34 UTC, Claudenw commented on src/test/java/org/apache/commons/collections4/bloomfilter/DefaultBloomFilterTest.java
> +                int limit = Integer.MAX_VALUE-1;
yes.  Fixed

2022-11-26 15:39 UTC, Claudenw commented on src/test/java/org/apache/commons/collections4/bloomfilter/DefaultBloomFilterTest.java
> +        for (int i=0; i<lastBits; i++) {
reworked - removed

2022-11-26 15:45 UTC, Claudenw commented on src/test/java/org/apache/commons/collections4/bloomfilter/DefaultBloomFilterTest.java
> +                int limit = Integer.MAX_VALUE-1;
No, if we set all the bits to 1 then we get an infinite result from the calculation.  This is to verify that when we have a very large estimage (larger than Integer.MAX_VALUE) we return Integer.MAX_VALUE.

2022-11-26 15:48 UTC, Claudenw commented on src/test/java/org/apache/commons/collections4/bloomfilter/DefaultBloomFilterTest.java
> +        // the actual result of the calculation is: 46144189292
It is noted here so that the test is understood to be verifying that larger than max int are returned as max int..
Comment updated.

2022-11-26 15:49 UTC, Claudenw commented on src/test/java/org/apache/commons/collections4/bloomfilter/DefaultBloomFilterTest.java
> +                int limit = Integer.MAX_VALUE-1;
Integer.MAX_VALUE returns an infinite value.  This is to test a value less than infinite.

2022-11-26 15:55 UTC, Claudenw commented on src/test/java/org/apache/commons/collections4/bloomfilter/DefaultBloomFilterTest.java
> +    public void testLargeBitmapAsArray() {
removed

2022-11-30 16:11 UTC, closed without merging